### ISSUE TITLE
User research report

### ISSUE THREAD

**Issue by srich-DWP** [dwpdigitaltech/service-dashboards#10]
Sort the findings from research sessions and complete a report.

**Comment by paulmsmith** [comment]
Nice one Richard.

**Comment by srich-DWP** [comment]
@paulmsmith how do I label this issue and add it to the project board?

**Comment by paulmsmith** [comment]
@srich-DWP It was possible you needed to be an admin for this repo. Just made you one. If you look to the right on this page, you should now see options with a little 'cog' icon.

**Comment by srich-DWP** [comment]
Can't see the cog, I might have to log out and and in again

**Comment by paulmsmith** [comment]
@srich-DWP Try now. I think you needed adding back to this repo properly after recent github thing that happened.

**Comment by srich-DWP** [comment]
Perfect mate, I got the cog !!
Thanks @paulmsmith
