### ISSUE TITLE
Update README to explain project

### ISSUE THREAD

**Issue by paulmsmith** [dwpdigitaltech/service-dashboards#3]
Wonder if @srich-DWP you want to update the default README.MD file to outline the work you/we are undertaking.

**Comment by paulmsmith** [comment]
Hey @srich-DWP do you think you could do this one? Thinking for people like @gavinelliott, that stumbled on the repository, it helps to updates these files with the purpose of the project. 👍

**Comment by srich-DWP** [comment]
Hey @paulmsmith README file has been updated with information about the repo. Should be self explanatory now. :-)

**Comment by paulmsmith** [comment]
Very good, cheers Rich.
