### ISSUE TITLE
Hold research sessions with Service Managers and Product Owners to identify needs for the dashboard

### ISSUE THREAD

**Issue by paulmsmith** [dwpdigitaltech/service-dashboards#6]
Hi @srich-DWP. Have you arranged this yet? It would be good to get the 'Prove you can apply team' and others involved.

cc: @gavinelliott @tsmorgan

**Comment by srich-DWP** [comment]
Started sessions with Service Managers and Product Managers. Outputs from 3  sessions have been captured, one more session next Wednesday with a Service Manager.

**Comment by srich-DWP** [comment]
Organised a session with Catherine Hope - analytics in Newcastle, to discuss ways in presenting the data to a dashboard. E.G which colours in graphs, pie charts, etc work well with users

**Comment by srich-DWP** [comment]
This issue can be closed. 
A report from the UR sessions will be put together
