### ISSUE TITLE
Heroku password

### ISSUE THREAD

**Issue by paulmsmith** [dwpdigitaltech/service-dashboards#8]
Hi Richard,

Have you set a password on the Heroku app? Can you set it to use the standard policy we have.

**Comment by paulmsmith** [comment]
Ignore. I think my browser had a wobble.

**Comment by srich-DWP** [comment]
Are you in Paul?
Username and password should be usual convention.

**Comment by paulmsmith** [comment]
Yep Rich, I closed this. Thanks for replying but an old extension in my browser was doing weird things. Sorted now.

**Comment by ivernus** [comment]
@paulmsmith @srich-DWP Can someone drop me a message/mail with the password. Would be interesting to see on big display we have here.

**Comment by paulmsmith** [comment]
Hi @ivernus. It's very early prototyping right now. Are you on XGov Slack, I can send you the login there.

**Comment by ivernus** [comment]
I am ya, thanks @paulmsmith there were too many Paul Smiths in the directory :)
